### ISSUE TITLE
Snyk generating false positives (not sure if plugin related or snyk cli related)

### ISSUE THREAD

**Issue by Simbaclaws** [snyk/snyk-visual-studio-plugin#135]
Hi there,

In my code somewhere I am using the function bypassSecurityTrustUrl and bypassSecurityTrustHTML because I am fetching content from a wisywig editor on one of my backends where the user needs to be able to style their own content with HTML.

Everywhere in my code I did this, snyk is giving me a warning about potential XSS security issues, which is good obviously.

However. All of these lines are directly put inside of a sanitize function that I am using with the exact same library that is using bypassSecurityTrustHTML and bypassSecurityTrustURL like so:

```typescript
this.sanitizer.sanitize(SecurityContext.HTML, this.sanitizer.bypassSecurityTrustHtml(myHtml));
```

where this.sanitizer is imported from: @angular/platform-browser

Whenever this sanitize is in front of it, it should be considered sanitized. The user in this case is explicitly sanitizing the content because they know they are fetching information from a wisywig editor on their backend infrastructure.

Should snyk not recognize this? And give an option saying: we found out you are already sanitizing this security issue. perhaps you want to ignore this issue? Or something like that? It is now effectively saying this in my editor:
```Unsanitized input from data from a remote resource.```
Which is just wrong.

Also please tell me whether this is an issue in the interface of this plugin, or whether it is related to for example the snyk cli not implementing this?

**Comment by Simbaclaws** [comment]
I'm also unable to ignore these issues in any of the files they are showing up in.
I have snyk set to automatically analyze, so I am guessing that there is a bug in the snyk plugin for vs code that when it is scanning file changes, it will show all of the issues again. Regardless of whether you have tried to ignore them.

**Comment by aldanchenko** [comment]
HI @Simbaclaws,

Thank you for feedback and your time 👍. 

Just to clarify: did you using Visual Studio or Visual Studio Code IDE?

Regards,
Alex

**Comment by Simbaclaws** [comment]
Apologies visual studio code isn't an IDE... I was using visual studio code.

**Comment by aldanchenko** [comment]
Thank you @Simbaclaws! I understand. I asked because we have another repo for VsCode. We will try to resolve the issue as soon as possible.

**Comment by michelkaporin** [comment]
Hi @Simbaclaws, please submit a ticket via our official support channel https://support.snyk.io/ to report false positive for Snyk Code product.

Feel free to raise another ticket for VS Code extension with the bug reproductions steps for the following report:
> I'm also unable to ignore these issues in any of the files they are showing up in.

**Comment by Simbaclaws** [comment]
I made 2 support tickets.

Hopefully someone will look into it :)

I'm sorry I couldn't contribute some code fixes, I'm pretty busy with some projects and don't know if I'd be good enough of a programmer to help diagnose and fix this issue. If I can find spare time, I'll try and see if I can help fix the issue.

**Comment by Simbaclaws** [comment]
Ok I just found out that the second issue about the warnings not disappearing, does actually disappear, but it's only doing it line by line. Regardless of whether you click the Ignore in this file button.

This is probably caused by the fact that I'm using a different parameter passed through one of the functions each time...

So for example:

```javascript
this.sanitizer.sanitize(SecurityContext.URL, this.sanitizer.bypassSecurityTrustUrl(this.newsUrl));
```` 
Whenever I do this on the this.newsUrl object and I ignore that "in the entire file".
I was expecting it would remove all of the lines in the file that contains: 
```javascript
this.sanitizer.sanitize(SecurityContext.URL, this.sanitizer.bypassSecurityTrustUrl(anyParam))
```

However since the param anyParam differs, it only removes those that have the exact same param.
Is this considered "By Design"? Or should this behave differently?

**Comment by Simbaclaws** [comment]
Can this issue perhaps be moved to: 
https://github.com/snyk/vscode-extension

I used the wrong repository apparently.
My bad...
