### ISSUE TITLE
snyk plugin has issues with windows 11 file paths

### ISSUE THREAD

**Issue by DaveLafleur** [snyk/snyk-visual-studio-plugin#146]
my files are here C:\Users\<user name>\source\repos

![image](https://user-images.githubusercontent.com/16905154/165756791-736112a4-b583-4875-b39f-a1643e1f3922.png)

**Comment by aldanchenko** [comment]
@DaveLafleur could you please try run cli on this directory and share results? It will help us understand is it common cli issue or only related to Visual Studio.

https://docs.snyk.io/snyk-cli

**Comment by DaveLafleur** [comment]
I checked windows updates, had one cumulative update which required a reboot.  testing the same operation after the patch and reboot seems to have cleared up some errors.

**Comment by aldanchenko** [comment]
Thank you for this update @DaveLafleur!
