### ISSUE TITLE
The SnykVSP package did not load correctly

### ISSUE THREAD

**Issue by akhilk-p** [snyk/snyk-visual-studio-plugin#175]
Getting this error while opening Snyk Plugin in VScode
![image](https://user-images.githubusercontent.com/75852843/173138252-779cbc24-3203-4b04-a468-d6e7908f1e4a.png)

And I am attaching the ActivityLog file along with this

[ActivityLog.txt](https://github.com/snyk/snyk-visual-studio-plugin/files/8881870/ActivityLog.txt)

**Comment by aldanchenko** [comment]
Hello @akhilk-p,

Thank you for submitting! Could you share more details with us? For example, could you send your log file to [support@snyk.io](mailto:support@snyk.io)? Please, specify in your email an ID or a link to this issue.

You could find extension log using [this info](https://github.com/snyk/snyk-visual-studio-plugin/#how-to-find-the-log-files).

Best regards,
Alex

**Comment by asaf92** [comment]
Hi @akhilk-p 
Are you using VS2017? Can you try updating to the latest VS2017 version and let us know if it solves it?

**Comment by akhilk-p** [comment]
@asaf92 Sure let me try

**Comment by asaf92** [comment]
> @asaf92 Sure let me try

Thanks, please let us know if it helped

**Comment by akhilk-p** [comment]
Hi @asaf92 

Last Friday I upgraded the application to VS2017  and now it's working fine, 
@aldanchenko @asaf92 thanks for your support

Best regards,
Akhil KP
