### ISSUE TITLE
No Supported Code Available

### ISSUE THREAD

**Issue by Xcaciv** [snyk/snyk-visual-studio-plugin#180]
I have reproduced this issue by simply checking out https://github.com/Xcaciv/dvta opening DVTA.sln and trying to scan it. There are blatant issues with the code like SQL Injection, but it does not see any files as scannable. The Snyk window shows the following: 
![image](https://user-images.githubusercontent.com/23732819/174405612-1f3a3b5d-7802-4362-8346-82707d5fa78f.png)
Log file attached
[snyk-extension.test.log](https://github.com/snyk/snyk-visual-studio-plugin/files/8931494/snyk-extension.test.log)

**Comment by aldanchenko** [comment]
Hi @Xcaciv,

Thank you!

**Comment by aldanchenko** [comment]
@Xcaciv I just want to double check that version of Snyk extension you use?

**Comment by Xcaciv** [comment]
I am using 1.1.20. I just updated to get the changes for SCA yesterday.

**Comment by aldanchenko** [comment]
Hi @Xcaciv 👋
 
We released new version (1.1.22) with the fix for this issue. Can you please install the new version and try it?
 
Best regards,
Alex

**Comment by michelkaporin** [comment]
Hi, since GitHub issues are not officially monitored by Snyk support, we will be disabling "Issues" tab on this repository very soon. 

Please raise the current issue directly by [contacting Snyk Support on the web](http://support.snyk.io) or emailing us at support@snyk.io.

**Comment by Xcaciv** [comment]
This does find files now. However, there are no results, and this is consistent with the CLI and SaaS for the sited repo.
