### ISSUE TITLE
Support for VS2022

### ISSUE THREAD

**Issue by as-jc** [snyk/snyk-visual-studio-plugin#69]
The extension does not currently support VS2022. When can we expect support for the latest version of Visual Studio?

**Comment by aldanchenko** [comment]
Hello @as-jc,

Thank you for feedback and for using our plugin! We currently working on VS2022 support. It will be available soon, maybe this week or next week.

Best regards,
Alex

**Comment by as-jc** [comment]
Thank you very much for the quick response @aldanchenko
