### ISSUE TITLE
VS - 2022

### ISSUE THREAD

**Issue by heldersantovisma** [snyk/snyk-visual-studio-plugin#72]
Hey!

In trying to use snyk scanner extension in VS 2022, but when I click Connect Visual Studio to Snyk.io it displays an error: "Invalid Guid: The system cannot find the file specified".

**Comment by heldersantovisma** [comment]
Looks a restart after the extension installation did the trick.

**Comment by aldanchenko** [comment]
Hi @heldersantovisma,

I'm glad it works for you! 👍 Could you share your log file (or part of log file with error) to investigate this issue?

How to find logs described here - 
https://github.com/snyk/snyk-visual-studio-plugin/tree/feat/snykcode-dev#how-to-find-the-log-files

Thank you!

Best regards,
Alex
