### ISSUE TITLE
Snyk keeps throwing NullReferenceException

### ISSUE THREAD

**Issue by David-McCarty** [snyk/snyk-visual-studio-plugin#93]
VS2022 (17.0.6)
Snyk 1.1.3
When I tell Snyk to scan, I get a banner at the top that says "Object reference not set to an instance of an object."
Final log entry:
EROR [141] SnykCodeService           Failed to obtain Snyk Code error message
System.NullReferenceException: Object reference not set to an instance of an object.

ALSO, it keeps wanting to download the latest Snyk CLI release, even though I can see that it is there in my "%HOMEPATH%\AppData\Local\Snyk\" folder

I have uninstalled the extension and reinstalled and still have the issue.

I exited VS, deleted everything in my "%HOMEPATH%\AppData\Local\Snyk\" folder and started VS again.  The resulting log file is attached (lightly redacted -- user and project data is replaced with xxx
[snyk-extension.log](https://github.com/snyk/snyk-visual-studio-plugin/files/8044757/snyk-extension.log)
)

**Comment by aldanchenko** [comment]
Hello @David-McCarty 

Thank you for such a detailed description! I researching the issue and will try to fix it soon.

**Comment by aldanchenko** [comment]
One additional question: this error `"Object reference not set to an instance of an object."` appears on all your projects or just one project? I think maybe extension can't process with some situations.

**Comment by aldanchenko** [comment]
Thanks @David-McCarty! From logs I see this errors is related to get project files functionality. It seems for some projects VS returns some null values.

**Comment by David-McCarty** [comment]
FYI: One of the projects that doesn't work is in an "organization" that I was not added to.  My admin just added me to that org and I thought that would allow Snyk to work on this project now, but it appears I am still getting the same error on that one.

Is there any fix, work around, or debugging steps you would like me try?

**Comment by aldanchenko** [comment]
Thanks @David-McCarty! I think it depends on project structure or project type. This project is VS solution project or you open it as folder? And maybe you could share is it WPF project or maybe ASP or other type?

**Comment by David-McCarty** [comment]
They are all VS solutions.  2 are windows services, 1 running on .NET Framework, and the other on .NET 6.  One is a solution with several different project types, but the start-up project is an ASP.NET web site.

**Comment by David-McCarty** [comment]
OK, I *think* I figured out what the problem is: All my solutions that have errors are ones that include an installer project.  I have installed the MS VS Installer projects extension (https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects) which allows a separate type of project file (with an extension .vdproj) that can be used to create an MSI installer.  Once I delete that project from my solution, Snyk seems to be happy.

It would seem that I should be able to tell Snyk to ignore this project by going to Tools->Options->Snyk->Project Settings and unchecking the box "Scan all projects", but (and maybe this is a new issue) when I uncheck it and hit OK and come right back, the box is checked again, so it doesn't seem to be saving my setting.  Also, I can't find anything that says what the empty text box above it it for. Would I list the projects it is supposed to scan in that box?  It doesn't seem to save anything, either...

**Comment by pmoran1947** [comment]
I am also seeing this problem. When I open the snyk window and it finishes downloading the cli, The run button is disblaed and the stop button is enabled. I click on the stop button and the run button is then enabled.
Click on the run button generates the nullreferenceexception.
I have attached the log 
[snyk-extension.log](https://github.com/snyk/snyk-visual-studio-plugin/files/8102583/snyk-extension.log)

The previous version os snyk I used worked fine.

**Comment by aldanchenko** [comment]
Thanks @pmoran1947! Revised the priority of this error. There will be a fix soon.

**Comment by aldanchenko** [comment]
Hi guys,

Just to keep you up to date. I found an issue related to NullReferenceException. We will try to publish new version soon. Unfortunately development process going really slow, because I'm in Ukraine and situation here is not so good.

Will keep you up to date :)

**Comment by aldanchenko** [comment]
Hi @David-McCarty,

We released new version with fix for issues. Please, try it. Thanks!

**Comment by aldanchenko** [comment]
Hi @pmoran1947 ,

We released new version (1.1.4) with fix for this issues. Please, try it. Thanks!

**Comment by pmoran1947** [comment]
I have just tried the new version and it seems to work without an nullreference exceptions

**Comment by David-McCarty** [comment]
> Hi @David-McCarty,
> 
> We released new version with fix for issues. Please, try it. Thanks!

It seems to be behaving much better now.  Thanks!

**Comment by aldanchenko** [comment]
If you don't mind I'll close this issue.
